driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: debian-7.8
  - name: centos-5.11
  - name: centos-6.6
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[firewall::default]
      - recipe[firewall-test::default]
    attributes:
      firewall:
        allow_ssh: true
