name              'firewall'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides a set of primitives for managing firewalls and associated rules.'
version           '7.0.3'
source_url        'https://github.com/sous-chefs/firewall'
issues_url        'https://github.com/sous-chefs/firewall/issues'
chef_version      '>= 15.5'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'
supports 'windows'
