name              'firewall'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides a set of primitives for managing firewalls and associated rules.'
version           '6.3.7'
source_url        'https://github.com/sous-chefs/firewall'
issues_url        'https://github.com/sous-chefs/firewall/issues'
chef_version      '>= 15.5'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'ubuntu'
supports 'windows'
